Repository conventional-changelog/conventional-changelog, pull requests merged in 2018-03, with the labels that each got.

#295 fix(preset): recommended-bump ESLint preset
  packages/conventional-changelog-eslint/conventional-recommended-bump.js
Labels: bug

#296 [Angular Package] Adapt to new Angular Commit Conventions
  packages/conventional-changelog-angular/README.md
  packages/conventional-changelog-angular/conventional-recommended-bump.js
  packages/conventional-changelog-angular/parser-opts.js
  packages/conventional-changelog-angular/test/test.js
  packages/conventional-changelog-angular/writer-opts.js
Labels: enhancement

#298 Remove anchor from header templates
  packages/conventional-changelog-angular/templates/header.hbs
  packages/conventional-changelog-atom/templates/header.hbs
  packages/conventional-changelog-codemirror/templates/header.hbs
  packages/conventional-changelog-ember/templates/header.hbs
  packages/conventional-changelog-eslint/templates/header.hbs
  packages/conventional-changelog-jquery/templates/header.hbs
  packages/conventional-changelog-jshint/templates/header.hbs
  packages/conventional-changelog-writer/README.md
  packages/conventional-changelog-writer/templates/header.hbs
  packages/conventional-changelog-writer/test/index.spec.js
  packages/conventional-changelog-writer/test/partial.header.spec.js
Labels: refactor

#287 Add license file
  LICENSE.md
  packages/conventional-changelog-angular/LICENSE.md
  packages/conventional-changelog-atom/LICENSE.md
  packages/conventional-changelog-codemirror/LICENSE.md
  packages/conventional-changelog-core/LICENSE.md
  packages/conventional-changelog-ember/LICENSE.md
  packages/conventional-changelog-eslint/LICENSE.md
  packages/conventional-changelog-express/LICENSE.md
  packages/conventional-changelog-jquery/LICENSE.md
  packages/conventional-changelog-jshint/LICENSE.md
  packages/conventional-changelog-preset-loader/LICENSE.md
  packages/conventional-changelog-writer/LICENSE.md
  packages/conventional-changelog/LICENSE.md
  packages/conventional-commits-parser/LICENSE.md
  packages/conventional-recommended-bump/LICENSE.md
  packages/git-raw-commits/LICENSE.md
  packages/git-semver-tags/LICENSE.md
  packages/gulp-conventional-changelog/LICENSE.md
  packages/standard-changelog/LICENSE.md
Labels: documentation, enhancement

#299 docs(conventional-changelog-cli): fix link to presets
  packages/conventional-changelog-cli/README.md
Labels: documentation
