Repository conventional-changelog/conventional-changelog, pull requests merged in 2018-02, with the labels that each got.

#278 fix(preset-loader): don't namespace exported function
  packages/conventional-changelog-preset-loader/index.js
  packages/conventional-changelog-preset-loader/test/test.js
Labels: bug

#270 feat: support `conventional-changelog-*` presets in `conventional-recommended-bump`
  packages/conventional-recommended-bump/.jshintrc
  packages/conventional-recommended-bump/README.md
  packages/conventional-recommended-bump/cli.js
  packages/conventional-recommended-bump/index.js
  packages/conventional-recommended-bump/index.spec.js
  packages/conventional-recommended-bump/package.json
  packages/conventional-recommended-bump/preset-resolver.js
  packages/conventional-recommended-bump/preset-resolver.spec.js
  packages/conventional-recommended-bump/presets/angular.js
  packages/conventional-recommended-bump/presets/eslint.js
  packages/conventional-recommended-bump/test/angular.js
  packages/conventional-recommended-bump/test/eslint.js
  packages/conventional-recommended-bump/test/prepare.js
  packages/conventional-recommended-bump/test/test.js
Labels: enhancement, needs: test

#284 fix(examples) updated broken example link
  packages/conventional-changelog-cli/README.md
Labels: type: docs

#289 chore(ci): match config between CI providers
  .travis.yml
  appveyor.yml
Labels: admin

#290 chore(package): enable Lerna hoisting and lockfiles
  .gitignore
  .travis.yml
  appveyor.yml
  package-lock.json
  package.json
  packages/conventional-changelog-angular/package-lock.json
  packages/conventional-changelog-atom/package-lock.json
  packages/conventional-changelog-cli/package-lock.json
  packages/conventional-changelog-codemirror/package-lock.json
  packages/conventional-changelog-core/package-lock.json
  packages/conventional-changelog-ember/package-lock.json
  packages/conventional-changelog-eslint/package-lock.json
  packages/conventional-changelog-express/package-lock.json
  packages/conventional-changelog-jquery/package-lock.json
  packages/conventional-changelog-jshint/package-lock.json
  packages/conventional-changelog-preset-loader/package-lock.json
  packages/conventional-changelog-writer/package-lock.json
  packages/conventional-changelog/package-lock.json
  packages/conventional-commits-filter/package-lock.json
  packages/conventional-commits-parser/package-lock.json
  packages/conventional-recommended-bump/package-lock.json
  packages/git-raw-commits/package-lock.json
  packages/git-semver-tags/package-lock.json
  packages/gulp-conventional-changelog/package-lock.json
  packages/standard-changelog/package-lock.json
Labels: admin
