Repository conventional-changelog/conventional-changelog, pull requests merged in 2018-08, with the labels that each got.

#361 fix: add missing context flag
  packages/conventional-changelog-cli/cli.js
Labels: defect

#350 feat(core): ability to reset changelog from scratch
  packages/conventional-changelog-core/lib/merge-config.js
  packages/conventional-changelog-core/test/test.js
Labels: enhancement

#345 fix(cli): pass `--tag-prefix` option to core
  packages/conventional-changelog-cli/cli.js
Labels: defect

#341 Fix typo - README.md
  packages/conventional-changelog-cli/README.md
Labels: documentation
