Repository conventional-changelog/conventional-changelog, pull requests merged in 2019-03, with the labels that each got.

#409 feat: send options to whatBump
  packages/conventional-recommended-bump/index.js
  packages/conventional-recommended-bump/test/index.spec.js
Labels: enhancement

#417 Docs: fixed link to eslint doc
  packages/conventional-changelog-eslint/README.md
Labels: documentation

#421 feat: creating specifically for conventionalcommits.org
  package-lock.json
  packages/conventional-changelog-conventionalcommits/LICENSE.md
  packages/conventional-changelog-conventionalcommits/README.md
  packages/conventional-changelog-conventionalcommits/conventional-changelog.js
  packages/conventional-changelog-conventionalcommits/conventional-recommended-bump.js
  packages/conventional-changelog-conventionalcommits/index.js
  packages/conventional-changelog-conventionalcommits/package.json
  packages/conventional-changelog-conventionalcommits/parser-opts.js
  packages/conventional-changelog-conventionalcommits/templates/commit.hbs
  packages/conventional-changelog-conventionalcommits/templates/footer.hbs
  packages/conventional-changelog-conventionalcommits/templates/header.hbs
  packages/conventional-changelog-conventionalcommits/templates/template.hbs
  packages/conventional-changelog-conventionalcommits/test/fixtures/_ghe-host.json
  packages/conventional-changelog-conventionalcommits/test/fixtures/_known-host.json
  packages/conventional-changelog-conventionalcommits/test/fixtures/_unknown-host.json
  packages/conventional-changelog-conventionalcommits/test/test.js
  packages/conventional-changelog-conventionalcommits/writer-opts.js
  packages/conventional-changelog-core/index.js
  packages/conventional-changelog/index.js
  packages/conventional-changelog/package.json
  packages/conventional-changelog/test/test.js
Labels: design, enhancement

#404 docs(eslint): added "Chore" tag
  packages/conventional-changelog-eslint/README.md
Labels: documentation
